module Problem0002
    ( main
    , fibonacci
    ) where

main :: IO ()
main = do
        putStrLn description
        putStrLn "The answer is:"
        print  . sum . filter odd . takeWhile (< 4000000) $ fibonacci

description = "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n\
\1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\
\By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.\n"

fibonacci :: [Integer]
fibonacci = 0 : 1 : zipWith (+) fibonacci (tail fibonacci)